name: Automate Preprocessing

# Trigger: Workflow akan jalan setiap kali kita push ke branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-process:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install library dari requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan script preprocessing otomatis
    - name: Run Preprocessing Script
      run: python preprocessing/automate_YustianasRombon.py

    # 5. Commit dan Push hasil data bersih kembali ke repo
    # Ini supaya hasil preprocessing tersimpan otomatis di folder 'water_potability_preprocessing'
    - name: Commit and Push Clean Data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add preprocessing/water_potability_preprocessing/water_potability_clean.csv
        # Hanya commit jika ada perubahan
        git commit -m "Auto-generated clean dataset by GitHub Actions" || echo "No changes to commit"
        git push